### ISSUE TITLE
Can't get WSL2 socket working

### ISSUE THREAD

**Issue by maicol07** [masahide/OmniSSHAgent#16]
Hi,
I've followed the WSL2 steps but it doesn't seem working:
```sh
$ source $HOME/omni-socat/ubuntu-bash.setup.sh
$ ssh-add -l
error fetching identities: communication with agent failed
```

However, it seems the `$SSH_AUTH_SOCK` has changed:
```sh
$ echo $SSH_AUTH_SOCK
/home/maicol07/.ssh/agent.sock
```

I'm using the 1Password proxy mode.
Can you help me?
Thanks

**Comment by maicol07** [comment]
I've also tried with MSYS2 and Git Bash and, although they use a different system to connect to the agent, I get:

```shell
$ ssh-add -l
Error connecting to agent: Permission denied
```

**Comment by maicol07** [comment]
@masahide any hint?

**Comment by masahide** [comment]
Is the setting "Enable Named pipe agent" enabled?
![image](https://user-images.githubusercontent.com/1309029/164888384-803c4292-8072-41a1-a095-3bb2cb11dff5.png)

**Comment by maicol07** [comment]
If I enable it, then 1Password proxy mode stops

**Comment by masahide** [comment]
Please check if socat is activated in WSL2.
```
~$ ps axuw |grep socat
masahide   317  0.0  0.0   6968  3444 ?        Ss   Apr17   0:00 socat UNIX-LISTEN:/home/masahide/.ssh/agent.sock,fork EXEC:/home/masahide/omni-socat/omni-socat.exe,nofork
```

**Comment by masahide** [comment]
To be sure, please check if the named pipe is running by using the following powershell command.
```
PS C:\Users\xxxx> Get-ChildItem \\.\pipe\|findstr open
------        1601/01/01      9:00              1 openssh-ssh-agent
```

**Comment by maicol07** [comment]
It worked for a bit but now doesn't work anymore.

Outputs:

```
~$ ps axuw |grep socat
maicol07   581  0.0  0.0  10280  4652 ?        Ss   11:22   0:00 socat UNIX-LISTEN:/home/maicol07/.ssh/agent.sock,fork EXEC:/home/maicol07/omni-socat/omni-socat.exe,nofork
maicol07  2955  0.0  0.0   6480  2168 pts/0    S+   11:46   0:00 grep --color=auto socat
```

```
PS C:\Users\Maicol> Get-ChildItem \\.\pipe\|findstr open
------        01/01/1601     01:00              1 openssh-ssh-agent
```

**Comment by maicol07** [comment]
Ok, I think I've found the issue. I currently use fish as default shell in WSL. When wsl boots it starts its own ssh-agent. When I enter bash works (and that because it correctly runs my `.bashrc`). When I exit the bash and return to fish, the old variables are back (since bash was a subshell).

Instead running `fish` from `bash` works since it inherit all the variables.

I would like to add a fish version of the bash script, however I'm a bit blocked with the main command substitution...

**Comment by masahide** [comment]
I'm sorry.
I only prepared the script for bash, so that's why.

**Comment by masahide** [comment]
I'm not sure I understand the syntax of fish,
The information on this page may be helpful. -> https://sean.mcgrath.nz/post/fish-shell-setup/
```
    setsid nohup socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"$HOME/omni-socat/omni-socat.exe" >/dev/null 2>&1 & disown
```

**Comment by maicol07** [comment]
Thank you! That works. I've also cleaned up a bit the script. Sending a PR now
