### ISSUE TITLE
OmniSSHAgent.exe: Please state more precisely the installation and usage of the (WIN) binary

### ISSUE THREAD

**Issue by stbuerger** [masahide/OmniSSHAgent#23]
First:  Thx a lot for the awesome solution!
I got it working quite well following the instruction in README.md Only thing a little unclear to me was "4. Run OmniSSHAgent.exe" under USAGE. As the "exe" is excutable as well as from within WSL and also from WIN11 environment, I needed one more attempt to get it working when running it from within WIN11. Still the following is not yet fully clear to me ..
- OmniSSHAgent needs to be started as the same user as the user invoking WSL. It does not work if started "as Administrator".
- After a system Re-Boot I need to start OmniSSHAgent at least once to make it work again. I can close it right after and it seems to  continue to work.
As of the first point it doesn't work running it as a Windows service, I'd like to know what would be a suitable/recommended way of starting the program after system restart. I assume that starting it as part of some "Run-at-Start" (Login) group would be the way to go. But I'd appriciate some guidance/instructions from expert how to best implement this.

thx
-stefan

**Comment by masahide** [comment]
Thank you for your detailed report.

I will modify the usage section based on the information you provided.

Unfortunately I am still using windows 10 and have not been able to confirm that it works with windows 11. 

> OmniSSHAgent needs to be started as the same user as the user invoking WSL. It does not work if started "as Administrator".

Failed to take into account execution with administrative privileges. It was created with the assumption that it would be executed with user privileges.
It was also not intended to be run as a Windows service.

> After a system Re-Boot I need to start OmniSSHAgent at least once to make it work again. I can close it right after and it seems to continue to work.

I have a few thoughts on this, so I'll check them out.

>  I'd like to know what would be a suitable/recommended way of starting the program after system restart. 

The following settings are recommended.
- press the Windows logo key  + R, type shell:startup, then select OK. This opens the Startup folder.
- Copy and paste the shortcut to the OmniSSHAgent .exe from the file location to the Startup folder.
https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd

**Comment by masahide** [comment]
[0dcf1e9](https://github.com/masahide/OmniSSHAgent/commit/0dcf1e9d1d3306664e6213a6e06e7085a939cb20) 
fix readme.

**Comment by masahide** [comment]
fix readme. affe131b9b4f848c197ed0fcdc7ebcc8b336267f

**Comment by stbuerger** [comment]
Thx a lot.
I can confirm that with this setup it perfectly works on WIN11 with native OpenSSH & WSL2 & Putty. Just be aware that it takes some time for the program to complete from (auto) start. So if you're in hurry with ssh after login it might not be ready yet. Just try again and it will work.

> The following settings are recommended.
> - press the Windows logo key  + R, type shell:startup, then select OK. This opens the Startup folder.
> - Copy and paste the shortcut to the OmniSSHAgent .exe from the file location to the Startup

**Comment by stbuerger** [comment]
Confirming that in addition to WSL2, OpenSSH, Putty it also works with ssh from MobaXterm if MbX configured for external (Pagent) ssh-agent.

**Comment by dtandersen** [comment]
Make sure to clear SSH_AUTH_SOCK. I had previously set it for pageant and it caused the windows ssh client to fail.
