### ISSUE TITLE
Populating duplicate tray entries

### ISSUE THREAD

**Issue by wfthkttn** [masahide/OmniSSHAgent#29]
Every time program restarts it populates tray icon duplicates in windows options (not the tray itself), and forgets if it has "visible" option checked.

I prefer to have all the tray icons visible, and drag tray icon out from 'hidden' to stay near keepass every time program restarts.
After several times doing that, it populated taskbar settings dialog quite a bit.  
![Screenshot 2022-10-19 025430](https://user-images.githubusercontent.com/30048666/196539679-b523b367-0ac8-41a5-aa1c-314707f6479e.png)

This may not be a bug since I've made some tweaks on my system, neither it is a real problem after selecting to show them all in `explorer shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}` windows dialog.

Also, if I restart Explorer, icon is gone for good.

Windows 11 pro build 22621.674

**Comment by masahide** [comment]
I have not tried it yet because I am not in a Windows 11 environment.
I will be upgrading to Windows 11 soon, so I will check it out.

**Comment by masahide** [comment]
I have tested the operation on Windows 11 and have confirmed the reproduction of this problem. We will investigate the cause.
@wfthkttn

**Comment by masahide** [comment]
This problem has been corrected.
@wfthkttn 
https://github.com/masahide/OmniSSHAgent/releases/tag/0.3.3

**Comment by masahide** [comment]
Duplicate entries could be removed by following the instructions at https://www.elevenforum.com/t/reset-taskbar-corner-notification-icons-in-windows-11.247/

**Comment by wfthkttn** [comment]
Works like a charm
