### ISSUE TITLE
Stopped working in windows 11

### ISSUE THREAD

**Issue by leonelcamara** [masahide/OmniSSHAgent#32]
Looks like a change in the webview or something.

![imagem](https://user-images.githubusercontent.com/1198145/226900962-fd9c7041-cb32-4211-892d-096632a6700b.png)

**Comment by masahide** [comment]
Under investigation.

**Comment by masahide** [comment]
I fixed it by updating the framework (wails) as soon as possible.
We would appreciate it if you could try it from [here](https://github.com/masahide/OmniSSHAgent/releases/tag/0.3.4).
@leonelcamara
