### ISSUE TITLE
ubuntu-bash.setup.sh improvements

### ISSUE THREAD

**Issue by ioqy** [masahide/OmniSSHAgent#41]
I have found two improvements that could be made to `ubuntu-bash.setup.sh`:
1. Install `unzip` (Because it was not installed in my debian WSL and the script didn't work)
2. Add `-f` to `rm omni-socat.zip` (Because I have the alias `rm='rm -i'` in my `.bashrc`, I get a prompt for deleting the file)

**Comment by masahide** [comment]
@ioqy 
Thank you.

Would this Pullreq change be ok?
