### ISSUE TITLE
omni-socat.exe cannot run when placed in the WSL filesystem

### ISSUE THREAD

**Issue by RAnders00** [masahide/OmniSSHAgent#50]
After #44, I still had the same issue one of my two machines. The socat process was running, but I found out that `omni-socat.exe` would not run:

```
ruben@RANDERS01:~$ ./omni-socat/omni-socat.exe
./omni-socat/omni-socat.exe: Invalid argument
                                             ruben@RANDERS01:~$
```

I eventually moved `omni-socat.exe` to `/mnt/c/omni-socat.exe`, changed the path in the bash script, and then it started working after a terminal restart.

I'm not sure how to debug this one to provide more details, so if you have any pointers, please let me know, I'll try my best to help debug this issue!

**Comment by masahide** [comment]
I tried adding a -l option to omni-socat.exe to add a mode that lists the keys of the agent. Can you check if it is possible to communicate now?

on WSL2
```bash
$ wget https://github.com/masahide/OmniSSHAgent/releases/download/v0.3.7/omni-socat.zip
$ unzip omni-socat.zip
$ ./omni-socat.exe -l
#1: ssh-ed25519 AAAA.............
```

**Comment by RAnders00** [comment]
Sadly, the same issue persists.

```
$ ./omni-socat.exe -l
./omni-socat.exe: Invalid argument
```

However, through more googling, I found out that this is a general issue with WSL and has hundreds of comments here: https://github.com/microsoft/WSL/issues/6170

The latest update appears to be that this issue has been fixed [*last week*](https://github.com/microsoft/WSL/issues/6170#issuecomment-1881881290), I will just have to wait until Microsoft releases WSL [2.1.0](https://github.com/microsoft/WSL/releases/tag/2.1.0). (Windows 11 seems to currently ship with 2.0.9.0)

**Comment by RAnders00** [comment]
In case it helps someone else... This issue was triggered by Docker for Windows. I uninstalled Docker, `wsl --shutdown`, waited 30 seconds, then when I opened the WSL terminal, everything worked just fine, including `ssh-add -l`.
